# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FlickrSearcher' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlickrSearcher
  pod 'Alamofire'
  pod 'PKHUD'
  pod 'SwiftyJSON'
end
