# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FlickrSearcher' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlickrSearcher
  pod 'Alamofire', '4.9.1'
  pod 'PKHUD', '5.3.0'
  pod 'SwiftyJSON', '5.0.0'
  pod 'Kingfisher', '5.9.0'
  pod 'CouchbaseLite-Swift', '2.7.0'
end
