//
//  PhotoWallPresenter.swift
//  FlickrSearcher
//
//  Created by CHI on 2020/1/26.
//  Copyright (c) 2020 CHI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoWallPresentationLogic {
    func presentLoadPhotos(response: PhotoWall.LoadPhotos.Response)
}

class PhotoWallPresenter: PhotoWallPresentationLogic {
    weak var viewController: PhotoWallDisplayLogic?
    func presentLoadPhotos(response: PhotoWall.LoadPhotos.Response) {
        var viewModel = PhotoWall.LoadPhotos.ViewModel()
        if let error = response.error {
            
        } else {
            var filckrPhotos:[PhotoWall.FlickrPhoto] = []
            response.photos.forEach() {
                filckrPhotos.append(PhotoWall.FlickrPhoto(json: $0))
            }
            viewModel.flickrPhotos = filckrPhotos
        }
        
        viewController?.displayLoadPhotos(viewModel: viewModel)
    }
}
