//
//  PhotoWallRouter.swift
//  FlickrSearcher
//
//  Created by CHI on 2020/1/26.
//  Copyright (c) 2020 CHI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PhotoWallRoutingLogic {
}

protocol PhotoWallDataPassing {
    var dataStore: PhotoWallDataStore? { get set }
}

class PhotoWallRouter: NSObject, PhotoWallRoutingLogic, PhotoWallDataPassing {
    weak var viewController: PhotoWallViewController?
    var dataStore: PhotoWallDataStore?
}
