//
//  PhotoWallViewController.swift
//  FlickrSearcher
//
//  Created by CHI on 2020/1/26.
//  Copyright (c) 2020 CHI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoWallDisplayLogic: class {
}

class PhotoWallViewController: UIViewController, PhotoWallDisplayLogic {
    var interactor: PhotoWallBusinessLogic?
    var router: (NSObjectProtocol & PhotoWallRoutingLogic & PhotoWallDataPassing)?
    var countPerPage: Int = 100

    // MARK: Object lifecycle
    init(keyword: String, countPerPage: Int) {
        super.init(nibName: nil, bundle: nil)
        title = "搜尋：\(keyword)"
        self.countPerPage = countPerPage
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = PhotoWallInteractor()
        let presenter = PhotoWallPresenter()
        let router = PhotoWallRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setUpAndLayoutViews()
    }
    
    private func setUpAndLayoutViews() {
        view.backgroundColor = .systemBackground
    }
}
