//
//  FavoriteModels.swift
//  FlickrSearcher
//
//  Created by CHI on 2020/2/3.
//  Copyright (c) 2020 CHI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Favorite {
    // MARK: Use cases
    enum FetchLocalPhoto {
        struct Request {}
        struct Response {
            var photos: [[String: Any]] = []
        }
        struct ViewModel{
            var localPhotos: [Photo] = []
        }
    }
    
    
    struct Photo {
        let flickrId: String
        let title: String
        let image: UIImage?
        
        init(flickrId: String, title: String, imageData: Data) {
            self.flickrId = flickrId
            self.title = title
            self.image = UIImage(data: imageData)
        }
    }
}
