//
//  SearchRouter.swift
//  FlickrSearcher
//
//  Created by CHI on 2020/1/25.
//  Copyright (c) 2020 CHI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
    func routeToPhotoWall(keyword: String, countPerPage: Int)
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
  
  // MARK: Routing
    func routeToPhotoWall(keyword: String, countPerPage: Int) {
        let photoWallViewController = SearchResultViewController(keyword: keyword, countPerPage: countPerPage)
        viewController?.navigationController?.pushViewController(photoWallViewController, animated: true)
    }
}
