//
//  PhotoWallRouter.swift
//  FlickrSearcher
//
//  Created by CHI on 2020/1/26.
//  Copyright (c) 2020 CHI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PhotoWallRoutingLogic {
}

protocol SearchResultDataPassing {
    var dataStore: SearchResultDataStore? { get set }
}

class SearchResultRouter: NSObject, PhotoWallRoutingLogic, SearchResultDataPassing {
    weak var viewController: SearchResultViewController?
    var dataStore: SearchResultDataStore?
}
