//
//  PhotoWallViewController.swift
//  FlickrSearcher
//
//  Created by CHI on 2020/1/26.
//  Copyright (c) 2020 CHI. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PKHUD

protocol SearchResultDisplayLogic: class {
    func displayLoadPhotos(viewModel: SearchResult.LoadPhotos.ViewModel)
}

class SearchResultViewController: UIViewController, SearchResultDisplayLogic {
    var interactor: SearchResultBusinessLogic?
    var router: (NSObjectProtocol & PhotoWallRoutingLogic & SearchResultDataPassing)?
    let keyword: String
    let countPerPage: Int

    // MARK: User interface elements
    lazy var collectionView: SearchResultCollectionView = {
        let collectionView = SearchResultCollectionView()
        return collectionView
    }()
    
    // MARK: Object lifecycle
    init(keyword: String, countPerPage: Int) {
        self.keyword = keyword
        self.countPerPage = countPerPage
        super.init(nibName: nil, bundle: nil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        self.keyword = ""
        self.countPerPage = 100
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = SearchResultInteractor(keyword: keyword, countPerPage: countPerPage)
        let presenter = SearchResultPresenter()
        let router = SearchResultRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setUpAndLayoutViews()
        loadPhotos()
    }
    
    private func setUpAndLayoutViews() {
        title = "搜尋：\(keyword)"
        view.backgroundColor = .systemBackground
        
        view.addSubview(collectionView)
        collectionView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor).isActive = true
        collectionView.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        collectionView.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        collectionView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor).isActive = true
    }
    
    private func loadPhotos() {
        HUD.show(.labeledProgress(title: nil, subtitle: "讀取中..."))
        let request = SearchResult.LoadPhotos.Request()
        interactor?.loadPhotos(request: request)
    }
    
    // MARK: Display logics
    func displayLoadPhotos(viewModel: SearchResult.LoadPhotos.ViewModel) {
        HUD.hide()
        if let errorMessage = viewModel.errorMessage {
            // to do: show error message
        } else {
            collectionView.photos.append(contentsOf: viewModel.flickrPhotos)
            collectionView.reloadData()
        }
    }
}
